# Generated by Django 3.0.3 on 2020-03-25 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='saved_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='capstone.Map'),
        ),
        migrations.CreateModel(
            name='CurrentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.Map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_map', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
