# Generated by Django 3.0.3 on 2020-03-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='position_x',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='position_y',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=100, null=True),
        ),
    ]
