# Generated by Django 3.0.3 on 2020-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20200323_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='industry',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booth',
            name='length_pixel',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booth',
            name='rotation',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='width_pixel',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, max_length=5),
            preserve_default=False,
        ),
    ]
