# Generated by Django 3.0.3 on 2020-03-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20200325_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentmap',
            name='actual_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actual_map', to='capstone.Map'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentmap',
            name='map_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_map_ref', to='capstone.Map'),
        ),
    ]
