# Generated by Django 3.0.3 on 2020-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20200323_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10, max_length=100),
        ),
        migrations.AlterField(
            model_name='booth',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10, max_length=100),
        ),
        migrations.AlterField(
            model_name='booth',
            name='rotation',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10, max_length=5),
        ),
    ]
