# Generated by Django 3.0.3 on 2020-03-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20200325_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmap',
            name='map_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curr_map_ref', to='capstone.Map'),
        ),
    ]
