# Generated by Django 3.0.3 on 2020-03-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20200323_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='saved_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='capstone.Map'),
            preserve_default=False,
        ),
    ]
