# Generated by Django 3.0.3 on 2020-03-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20200325_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentMap',
        ),
    ]
