# Generated by Django 3.0.3 on 2020-03-24 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0005_auto_20200324_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
